N_CLASSROOMS = 3
LECTURE_NOMINAL_END_TIME = "11:00 AM" 

BOTTLENECK_CAPACITY_PER_MINUTE = 30 
SLOT_DURATION_MINUTES = 2          
MAX_STUDENTS_PER_SLOT = BOTTLENECK_CAPACITY_PER_MINUTE * SLOT_DURATION_MINUTES 

INITIAL_ATTENDANCE = [40, 55, 60] 
VIOLATION_LIMIT = 7 
MAX_NEGOTIATION_ROUNDS = 10 

SIMULATION_EPISODES = 4 